# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@Word1
    ports:
      - 1433:1433
  
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672


  orderconsumer:
    image: orderconsumer
    build:
      context: .
      dockerfile: FreakyFashionServices.OrderService.Consumer/Dockerfile
    ports:
      - 5673:80
    depends_on:
      - db
      - rabbit
  
  orderproducer:
    image: orderproducer
    build:
      context: .
      dockerfile: FreakyFashionServices.OrderService.Producer/Dockerfile
    ports:
      - 5000:80    
  
