# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  
  catalogDb:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@Word1
    ports:
      - 1433:1433

  orderDb:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@Word1
    ports:
      - 1434:1433      
  
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  redis:
    image: redis
    ports:
      - 6379:6379

  orderconsumer:
    image: orderconsumer
    build:
      context: .
      dockerfile: FreakyFashionServices.OrderService.Consumer/Dockerfile
    ports:
      - 5673:80
    depends_on:
      - orderDb
      - rabbit
  
  orderproducer:
    image: orderproducer
    build:
      context: .
      dockerfile: FreakyFashionServices.OrderService.Producer/Dockerfile
      
  
  gateway:
    image: gateway
    build:
        context: .
        dockerfile: FreakyFashionServices.Gateway/Dockerfile
    ports:
      - 5000:80 
        
  productprice:
    image: productprice
    build:
      context: .
      dockerfile: FreakyFashionServices.ProductPrice/Dockerfile
      
  catalog:
    image: catalog
    build: 
      context: .
      dockerfile: FreakyFashionServices.Catalog/Dockerfile
    depends_on:
      - catalogDb
      
  basket:
    image: basket
    build:
      context: .
      dockerfile: FreakyFashionServices.Basket/Dockerfile
  
    depends_on:
      - redis

     