# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@Word1
    ports:
      - 1433:1433
    volumes:
      - /Users/fransengstrom/Desktop/sqlserver:/var/opt/mssql

  freakyfashionservicescatalog:
    image: freakyfashionservicescatalog
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - db
